"""
The logical connection model: ports, the edges between them, and gather specs.

This is the bottom of the pipeline package. It describes what a connection
*means* -- a produced value, an alias forwarding an already-known one, or a
compile-time many-to-one gather -- without knowing anything about the concrete
processes that own the ports. Port parents are duck-typed through
``__node_type__`` on purpose, so this layer never imports the process layer.
"""

from __future__ import annotations

import os
import typing
from dataclasses import dataclass
# From collections.abc, not typing: `isinstance(x, typing.Mapping)` gives a
# type checker no class to narrow on, so a `str | Mapping` union stays a union
# inside the isinstance branch and every `key['src']` looks like an error. The
# typing aliases have been deprecated since 3.9 in any case.
from collections.abc import Mapping, Sequence
from typing import Any, cast

import ubelt as ub

Collection = Mapping[str, Any] | Sequence[Any] | set[Any] | None
Configurable = dict[str, Any] | None

#: One ``GatherSpec.group_by`` entry as a caller writes it: a plain name used
#: on both sides of the edge, or ``{'src': ..., 'dst': ...}`` when each side
#: calls it something different.
GroupByKey = str | Mapping[str, str]

#: The same entry once stored. A mapping is normalized to a pair so the spec
#: stays hashable -- it is used as a dict key when reporting cardinalities.
StoredGroupByKey = str | tuple[str, str]
@dataclass(frozen=True)
class GatherSpec:
    """
    Compile-time many-to-one connection semantics.

    A gather partitions configured source-node instances by ``group_by`` and
    binds each group to the target node instance with the same parameter
    values. The resulting source paths are delivered to the target as a
    newline-delimited path manifest generated by kwdagger.

    Args:
        group_by:
            Parameter names shared by the source and target nodes. An empty
            sequence gathers all source instances into each target collection.
            An entry may instead be ``{'src': ..., 'dst': ...}`` when the two
            sides name the same thing differently (see
            :func:`_store_group_key`).
        order_by:
            Optional source parameter names used to order manifest members.
            When omitted, members are ordered by source process id.
        require:
            Completion policy. Version 1 supports only ``"all_success"``.
    """

    group_by: tuple[StoredGroupByKey, ...]
    order_by: tuple[str, ...] = ()
    require: str = 'all_success'

    def __init__(
        self,
        group_by: Sequence[GroupByKey],
        order_by: Sequence[str] | None = None,
        require: str = 'all_success',
    ) -> None:
        if isinstance(group_by, (str, bytes)):
            raise TypeError('GatherSpec.group_by must be a sequence of names')
        if isinstance(order_by, (str, bytes)):
            raise TypeError('GatherSpec.order_by must be a sequence of names')
        order_by_ = tuple(order_by or ())
        # Validate before normalizing, so a malformed entry gets the specific
        # message below rather than a KeyError from the normalization.
        for key in group_by:
            if isinstance(key, Mapping):
                if set(key) != {'src', 'dst'}:
                    raise ValueError(
                        'A mapping group_by item must have exactly "src" and '
                        f'"dst" keys; got {sorted(key)}'
                    )
                if not all(
                    isinstance(v, str) and v for v in key.values()
                ):
                    raise TypeError(
                        'group_by src/dst values must be non-empty strings'
                    )
            elif not (isinstance(key, str) and key):
                raise TypeError(
                    'GatherSpec.group_by items must be non-empty strings or '
                    '{"src": ..., "dst": ...} mappings'
                )
        if not all(isinstance(k, str) and k for k in order_by_):
            raise TypeError(
                'GatherSpec.order_by items must be non-empty strings'
            )
        # Mapping entries become (src, dst) pairs so the spec stays hashable
        # -- it is used as a dict key when reporting cardinalities.
        group_by_ = tuple(_store_group_key(key) for key in group_by)
        _seen = [_group_key_pair(k) for k in group_by_]
        if len(set(_seen)) != len(_seen):
            raise ValueError('GatherSpec.group_by cannot contain duplicates')
        if len(set(order_by_)) != len(order_by_):
            raise ValueError('GatherSpec.order_by cannot contain duplicates')
        if require != 'all_success':
            raise ValueError(
                'GatherSpec.require currently supports only "all_success"; '
                f'got {require!r}'
            )
        object.__setattr__(self, 'group_by', group_by_)
        object.__setattr__(self, 'order_by', order_by_)
        object.__setattr__(self, 'require', require)

    @classmethod
    def coerce(cls, data: Any) -> 'GatherSpec':
        if isinstance(data, cls):
            return data
        if isinstance(data, Mapping):
            return cls(**dict(data))
        raise TypeError(
            f'Cannot coerce {type(data).__name__} into GatherSpec: {data!r}'
        )

    def display_keys(self) -> tuple[str, ...]:
        """Human-readable group keys, e.g. ``dataset_fpath->truth_fpath``."""
        out = []
        for key in self.group_by:
            src, dst = _group_key_pair(key)
            out.append(src if src == dst else f'{src}->{dst}')
        return tuple(out)

    def source_keys(self) -> tuple[str, ...]:
        """The key resolved on each *source* instance, in order."""
        return tuple(_group_key_pair(k)[0] for k in self.group_by)

    def target_keys(self) -> tuple[str, ...]:
        """The key resolved on the *target* instance, in order."""
        return tuple(_group_key_pair(k)[1] for k in self.group_by)

    def to_dict(self) -> dict[str, Any]:
        data: dict[str, Any] = {
            'group_by': [
                {'src': k[0], 'dst': k[1]} if isinstance(k, tuple) else k
                for k in self.group_by
            ]
        }
        if self.order_by:
            data['order_by'] = list(self.order_by)
        if self.require != 'all_success':
            data['require'] = self.require
        return data


def _store_group_key(key: GroupByKey) -> StoredGroupByKey:
    """
    Put an authored ``group_by`` entry into the form :class:`GatherSpec` stores.

    A plain string names the same thing on both sides and is kept as-is. A
    ``{'src': ..., 'dst': ...}`` mapping lets each side name it in its own
    vocabulary -- a scorer whose truth port is ``truth_fpath`` can group
    predictions keyed on ``dataset_fpath`` without either node renaming a port
    to satisfy the other -- and becomes a pair, because the spec is frozen and
    used as a dict key while a mapping is unhashable.

    Callers must validate first: a mapping without both keys raises ``KeyError``
    here, where :meth:`GatherSpec.__init__` raises something explanatory.

    Args:
        key (GroupByKey): one entry as written.

    Returns:
        StoredGroupByKey

    Example:
        >>> _store_group_key('task')
        'task'
        >>> _store_group_key({'src': 'dataset_fpath', 'dst': 'truth_fpath'})
        ('dataset_fpath', 'truth_fpath')
    """
    if isinstance(key, str):
        return key
    return (key['src'], key['dst'])


def _group_key_pair(key: StoredGroupByKey) -> tuple[str, str]:
    """
    Read a stored ``group_by`` entry as ``(source_key, target_key)``.

    Args:
        key (StoredGroupByKey): one entry as :class:`GatherSpec` stores it.

    Returns:
        tuple[str, str]

    Example:
        >>> _group_key_pair('task')
        ('task', 'task')
        >>> _group_key_pair(('dataset_fpath', 'truth_fpath'))
        ('dataset_fpath', 'truth_fpath')
    """
    if isinstance(key, str):
        return (key, key)
    return key


@dataclass
class GatherConnection:
    """A template-level gather edge between an output and an input port."""

    source: Any
    target: Any
    spec: GatherSpec
def _dependency_preds(input_node: Any) -> list:
    """
    Predecessors of an input that represent a real data dependency.

    An ``input -> input`` edge is an *alias*: the upstream node does not
    produce this value, it merely consumes the same one. Treating that as a
    dependency would make the consumer inherit the producer's identity --
    including sweep axes it never reads -- so aliases are excluded here.
    """
    return [pred for pred in input_node.pred if not isinstance(pred, InputNode)]


def _alias_preds(input_node: Any) -> list:
    """Predecessors of an input that only share its value."""
    return [pred for pred in input_node.pred if isinstance(pred, InputNode)]


def _produced_origins(input_node: Any) -> list:
    """
    Every :class:`OutputNode` whose product ultimately supplies this input.

    An ``input -> input`` edge forwards an already-known value, and when that
    value is externally configured or comes from a declared default there is
    nothing to wait for. But an alias may equally well forward a value some
    process *produces*, and that producer still has to run and materialize
    its artifact first. Aliasing a port must not erase the producer standing
    behind it.

    Origins are found structurally, by walking alias edges backwards to the
    output ports they end at. Nothing is resolved along the way, so the
    answer cannot depend on node insertion order, on whether the pipeline has
    been configured yet, or on a value left over from a previously configured
    matrix row. It is the single place this traversal is written: dependency,
    identity, and provenance all ask here.

    Note that the process *holding* an aliased input is not itself an origin
    when it merely lends a value it also consumes. A *gathered* port is the
    exception: its value is the manifest that port's own job writes, so the
    process holding it really does produce the artifact being forwarded, and
    the gathered port is returned as the origin.

    Args:
        input_node (InputNode): the port to trace.

    Returns:
        list: the direct producers of this port, in declaration order,
            followed by any recovered through aliases, ordered by port key.
            Entries are :class:`OutputNode` ports, or an :class:`InputNode`
            when the origin is a gather manifest. Both answer ``.parent`` and
            ``.name``; use :func:`_origin_kind` to tell them apart.
    """
    direct = {id(pred): pred for pred in _dependency_preds(input_node)}
    recovered: dict[int, Any] = {}

    seen = {id(input_node)}
    stack = list(_alias_preds(input_node))
    while stack:
        alias = stack.pop()
        if id(alias) in seen:
            # Alias relationships are validated as acyclic elsewhere, but a
            # traversal that is only correct on a DAG is a trap for later
            # callers.
            continue
        seen.add(id(alias))
        if alias._gather_members is not None:
            # A gathered port resolves to a manifest, and that manifest is
            # written by the job that owns the port -- not by any member of
            # the collection. Forwarding it therefore does create a real
            # dependency on that job, and the traversal stops here: whatever
            # the members are, they are already that job's own ancestors.
            recovered[id(alias)] = alias
            continue
        for pred in _dependency_preds(alias):
            recovered[id(pred)] = pred
        stack.extend(_alias_preds(alias))

    origins = list(direct.values())
    origins += sorted(
        (port for key, port in recovered.items() if key not in direct),
        key=lambda port: port.key,
    )
    return origins


def _origin_kind(port: Any) -> str:
    """
    Say what kind of artifact an origin from :func:`_produced_origins` is.

    Both kinds are produced by the job that owns the port, but they are not
    the same thing and identity must not confuse them: an ``'output'`` is a
    declared output path, a ``'gather_manifest'`` is the path manifest a
    gathered input port writes as part of its own consumer's command.
    """
    return 'output' if isinstance(port, OutputNode) else 'gather_manifest'


def _origin_identity_bindings(input_node: Any) -> list[dict[str, Any]]:
    """
    The canonical identity contribution of everything that produces an input.

    An input whose value is produced upstream must carry *which* upstream
    instance produced it. The ancestor payload alone cannot: it records
    ``algo_id``, which is deliberately blind to the producer's own inputs, so
    two producers that run the same algorithm over different data look
    identical there. Without this, two consumers reading different files
    would hash to one ``process_id`` and share a result directory.

    Deterministically ordered, so the payload does not depend on the order
    ports were connected.

    Args:
        input_node (InputNode): the port to describe.

    Returns:
        list: one record per producing port; empty when nothing produces it.
    """
    bindings = [
        {
            'source_process_id': port.parent.process_id,
            'source_port': port.name,
            'source_kind': _origin_kind(port),
        }
        for port in _produced_origins(input_node)
    ]
    bindings.sort(
        key=lambda item: (
            item['source_process_id'],
            item['source_kind'],
            item['source_port'],
        )
    )
    return bindings


class Node(ub.NiceRepr):
    """
    Abstract base class for a Process or IO Node.
    """

    __node_type__ = 'abstract'  # used to workaround IPython isinstance issues

    def __nice__(self) -> str:
        return f'{self.name!r}, pred={[n.name for n in self.pred]}, succ={[n.name for n in self.succ]}'

    def __init__(self, name: Any) -> None:
        self.name = name
        self.pred: list[Any] = []
        self.succ: list[Any] = []

    def _connect_single(
        self, other: Any, src_map: Mapping[str, str], dst_map: Mapping[str, str]
    ) -> None:
        """
        Handles connection rules between this node and another one.

        TODO: cleanup, these rules are too complex and confusing.
        There is a reasonable subset here; find and restrict to that.
        """
        # Keep parameter forwarding distinct from filesystem IO. The generic
        # connection machinery predates parameter ports and otherwise accepts
        # nonsensical output->parameter or parameter->input edges that only
        # fail later during configuration.
        if isinstance(self, ParamNode) or isinstance(other, ParamNode):
            if not isinstance(self, ParamNode) or not isinstance(
                other, ParamNode
            ):
                raise TypeError(
                    'Algorithm parameter ports may only connect to other '
                    f'algorithm parameter ports; got {self.key!r} -> '
                    f'{other.key!r}'
                )

        # TODO: CLEANUP
        # print(f'Connect {type(self).__name__} {self.name} to '
        #       f'{type(other).__name__} {other.name}')
        if other not in self.succ:
            self.succ.append(other)
        if self not in other.pred:
            other.pred.append(self)

        self_is_proc = self.__node_type__ == 'process'
        if self_is_proc:
            # ``outputs`` lives on ProcessNode, not the base Node; access it
            # dynamically (guarded by __node_type__) to stay well-typed.
            assert hasattr(self, 'outputs')
            outputs = getattr(self, 'outputs')
        else:
            assert self.__node_type__ == 'io'
            outputs = {self.name: self}

        other_is_proc = other.__node_type__ == 'process'
        if other_is_proc:
            inputs = other.inputs
        else:
            assert other.__node_type__ == 'io'
            if not self_is_proc:
                # In this case we can make the name map implicit
                inputs = {self.name: other}
            else:
                inputs = {other.name: other}

        assert isinstance(outputs, typing.Mapping)
        src_map = cast(Any, src_map)
        dst_map = cast(Any, dst_map)
        outmap = ub.udict({src_map.get(k, k): k for k in outputs.keys()})
        inmap = ub.udict({dst_map.get(k, k): k for k in inputs.keys()})

        common = outmap.keys() & inmap.keys()
        if len(common) == 0:
            print('inmap = {}'.format(ub.urepr(inmap, nl=1)))
            print('outmap = {}'.format(ub.urepr(outmap, nl=1)))
            raise Exception(
                f'Unknown io relationship {self.name=}, {other.name=}'
            )

        if self_is_proc or other_is_proc:
            # print(f'Connect Process to Process {self.name=} to {other.name=}')
            self_output_keys = (outmap & common).values()  # type: ignore
            other_input_keys = (inmap & common).values()  # type: ignore

            for out_key, in_key in zip(self_output_keys, other_input_keys):
                out_node = outputs[out_key]
                in_node = inputs[in_key]
                # out_node._connect_single(in_node, src_map, dst_map)
                assert hasattr(out_node, '_connect_single')
                out_node._connect_single(in_node, {}, {})

    def connect(
        self,
        *others: Any,
        param_mapping: Mapping[str, str] | None = None,
        src_map: Mapping[str, str] | None = None,
        dst_map: Mapping[str, str] | None = None,
        gather: GatherSpec | Mapping[str, Any] | None = None,
    ) -> 'Node':
        """
        Connect the outputs of ``self`` to the inputs of ``others``.

        Conceptually, this creates an edge between the two nodes. When
        ``gather`` is given, the edge is a compile-time many-to-one edge and
        must connect one :class:`OutputNode` to one or more
        :class:`InputNode` objects.
        """
        # Connect these two nodes and return the original.
        if param_mapping is None:
            param_mapping = {}

        if src_map is None:
            src_map = param_mapping

        if dst_map is None:
            dst_map = param_mapping

        if gather is None:
            for other in others:
                self._connect_single(other, src_map, dst_map)
        else:
            gather_spec = GatherSpec.coerce(gather)
            if not isinstance(self, OutputNode):
                raise TypeError(
                    'Gather connections must originate from an OutputNode; '
                    f'got {type(self).__name__}'
                )
            for other in others:
                if not isinstance(other, InputNode):
                    raise TypeError(
                        'Gather connections must terminate at an InputNode; '
                        f'got {type(other).__name__}'
                    )
                if other.pred:
                    raise ValueError(
                        f'Cannot gather into {other.key!r}: it already has an '
                        'ordinary predecessor'
                    )
                if other._gather_connection is not None:
                    raise ValueError(
                        f'Input {other.key!r} already has a gather connection'
                    )
                connection = GatherConnection(self, other, gather_spec)
                self._gather_connections.append(connection)
                other._gather_connection = connection

        return self

    @property
    def key(self) -> str:
        return self.name


class _UnsetValue:
    """Singleton sentinel for a port with no explicit local value."""

    def __deepcopy__(self, memo: Any) -> '_UnsetValue':
        return self

    def __repr__(self) -> str:
        return '<unset>'


_UNSET = _UnsetValue()


def _coerce_comparable_value(value: Any) -> Any:
    """Normalize common path-like values before conflict checks."""
    if isinstance(value, os.PathLike):
        return os.fspath(value)
    return value


def _config_values_equal(left: Any, right: Any) -> bool:
    """Robust equality for values used by shared configuration ports."""
    left = _coerce_comparable_value(left)
    right = _coerce_comparable_value(right)
    try:
        equal = left == right
        if isinstance(equal, bool):
            return equal
        if hasattr(equal, 'all'):
            return bool(equal.all())
        return bool(equal)
    except Exception:
        return repr(left) == repr(right)


class IONode(Node):
    __node_type__ = 'io'

    def __init__(
        self, name: str, parent: Any, default_value: Any = _UNSET
    ) -> None:
        super().__init__(name)
        self.parent = parent
        self.default_value = default_value
        self._final_value = _UNSET
        self._template_value = None
        self._gather_connection: GatherConnection | None = None
        self._gather_members: list[Any] | None = None

    def _shared_value_predecessors(self) -> list[Any]:
        """Predecessors that forward an already-known configuration value."""
        return []

    def _shared_value(self) -> Any:
        predecessors = self._shared_value_predecessors()
        if not predecessors:
            return _UNSET
        # A predecessor that resolves to nothing supplies nothing. Only ports
        # that actually carry a value can agree or disagree about it.
        bound = [(pred, pred._resolved_value()) for pred in predecessors]
        bound = [item for item in bound if item[1] is not _UNSET]
        if not bound:
            return _UNSET
        first = bound[0][1]
        if not all(
            _config_values_equal(first, value) for _pred, value in bound[1:]
        ):
            bindings = {pred.key: value for pred, value in bound}
            raise ValueError(
                f'Conflicting shared values for {self.key!r}: {bindings!r}'
            )
        return first

    @property
    def final_value(self) -> Any:
        """
        The value this port resolves to, or ``None`` when nothing supplies one.

        Use :func:`_resolved_value` when the difference between "resolved to
        ``None``" and "nothing supplied a value" matters.
        """
        value = self._resolved_value()
        return None if value is _UNSET else value

    def _resolved_value(self) -> Any:
        """
        Resolve this port, returning ``_UNSET`` when nothing supplies a value.

        The precedence is: a gathered manifest, this port's own configured
        value, a shared value forwarded from a peer port, a value produced by
        an upstream process, and finally the declared default.
        """
        if self._gather_members is not None:
            return self.gather_manifest_fpath
        local_value = self._final_value
        shared_value = self._shared_value()
        if local_value is not _UNSET and shared_value is not _UNSET:
            if not _config_values_equal(local_value, shared_value):
                source_values = {
                    pred.key: pred.final_value
                    for pred in self._shared_value_predecessors()
                }
                raise ValueError(
                    f'Conflicting explicit and shared values for {self.key!r}: '
                    f'explicit={local_value!r}, shared={source_values!r}'
                )
            return local_value
        if local_value is not _UNSET:
            return local_value
        if shared_value is not _UNSET:
            return shared_value

        # Produced inputs preserve the historical behavior: one predecessor
        # forwards one path, and multiple predecessors form a collection.
        shared_predecessors = self._shared_value_predecessors()
        produced_preds = [
            pred for pred in self.pred if pred not in shared_predecessors
        ]
        if produced_preds:
            if len(produced_preds) == 1:
                return produced_preds[0].final_value
            return [pred.final_value for pred in produced_preds]
        return self.default_value

    @final_value.setter
    def final_value(self, value: Any) -> None:
        self._final_value = value

    @property
    def key(self) -> str:
        return self.parent.key + '.' + self.name

    @property
    def gather_manifest_fpath(self) -> Any:
        if self._gather_members is None:
            raise AttributeError(
                f'{self.key!r} is not a configured gather input'
            )
        return self.parent.final_node_dpath / '_gather' / f'{self.name}.txt'

    def gather_manifest_text(self) -> str:
        if self._gather_members is None:
            raise AttributeError(
                f'{self.key!r} is not a configured gather input'
            )
        paths = [
            os.fspath(member.final_value) for member in self._gather_members
        ]
        for path in paths:
            if '\n' in path:
                raise ValueError(
                    f'Gathered path contains a newline and cannot be represented '
                    f'in a path manifest: {path!r}'
                )
        return ''.join(path + '\n' for path in paths)


class InputNode(IONode):
    def _shared_value_predecessors(self) -> list[Any]:
        return [pred for pred in self.pred if isinstance(pred, InputNode)]


class ParamNode(IONode):
    """A connectable algorithm parameter, distinct from a filesystem input."""

    def _shared_value_predecessors(self) -> list[Any]:
        return [pred for pred in self.pred if isinstance(pred, ParamNode)]


class OutputNode(IONode):
    def __init__(self, name: str, parent: Any) -> None:
        super().__init__(name, parent)
        self._gather_connections: list[GatherConnection] = []

    # Redefine as a full read-write property (getter + setter) so it remains a
    # Liskov-compatible override of IONode's read-write ``final_value`` -- a
    # plain ``@property`` would drop the setter and trip the type checkers.
    @property
    def final_value(self) -> Any:
        # return self.parent._finalize_templates()['out_paths'][self.name]
        return self.parent.final_out_paths[self.name]

    @final_value.setter
    def final_value(self, value: Any) -> None:
        self._final_value = value

    def _resolved_value(self) -> Any:
        # An output port always resolves: the process defines where it writes.
        return self.final_value

    @property
    def template_value(self) -> Any:
        return self.parent.template_out_paths[self.name]
