"""
The logical connection model: ports, the edges between them, and gather specs.

This is the bottom of the pipeline package. It describes what a connection
*means* -- a produced value, an alias forwarding an already-known one, or a
compile-time many-to-one gather -- without knowing anything about the concrete
processes that own the ports. Port parents are duck-typed through
``__node_type__`` on purpose, so this layer never imports the process layer.
"""

from __future__ import annotations

import os

# From collections.abc, not typing: `isinstance(x, typing.Mapping)` gives a
# type checker no class to narrow on, so a `str | Mapping` union stays a union
# inside the isinstance branch and every `key['src']` looks like an error. The
# typing aliases have been deprecated since 3.9 in any case.
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Any, cast

import ubelt as ub

Collection = Mapping[str, Any] | Sequence[Any] | set[Any] | None
Configurable = dict[str, Any] | None

#: One ``GatherSpec.group_by`` entry as a caller writes it: a plain name used
#: on both sides of the edge, or ``{'src': ..., 'dst': ...}`` when each side
#: calls it something different.
GroupByKey = str | Mapping[str, str]

#: The same entry once stored. A mapping is normalized to a pair so the spec
#: stays hashable -- it is used as a dict key when reporting cardinalities.
StoredGroupByKey = str | tuple[str, str]


@dataclass(frozen=True)
class GatherSpec:
    """
    Compile-time many-to-one connection semantics.

    A gather partitions configured source-node instances by ``group_by`` and
    binds each group to the target node instance with the same parameter
    values. The resulting source paths are delivered to the target as a
    newline-delimited path manifest generated by kwdagger.

    Args:
        group_by:
            Parameter names shared by the source and target nodes. An empty
            sequence gathers all source instances into each target collection.
            An entry may instead be ``{'src': ..., 'dst': ...}`` when the two
            sides name the same thing differently (see
            :func:`_store_group_key`).
        order_by:
            Optional source parameter names used to order manifest members.
            When omitted, members are ordered by source process id.
        require:
            Completion policy. Version 1 supports only ``"all_success"``.
    """

    group_by: tuple[StoredGroupByKey, ...]
    order_by: tuple[str, ...] = ()
    require: str = 'all_success'

    def __init__(
        self,
        group_by: Sequence[GroupByKey],
        order_by: Sequence[str] | None = None,
        require: str = 'all_success',
    ) -> None:
        if isinstance(group_by, (str, bytes)):
            raise TypeError('GatherSpec.group_by must be a sequence of names')
        if isinstance(order_by, (str, bytes)):
            raise TypeError('GatherSpec.order_by must be a sequence of names')
        order_by_ = tuple(order_by or ())
        # Validate before normalizing, so a malformed entry gets the specific
        # message below rather than a KeyError from the normalization.
        for key in group_by:
            if isinstance(key, Mapping):
                if set(key) != {'src', 'dst'}:
                    raise ValueError(
                        'A mapping group_by item must have exactly "src" and '
                        f'"dst" keys; got {sorted(key)}'
                    )
                if not all(isinstance(v, str) and v for v in key.values()):
                    raise TypeError(
                        'group_by src/dst values must be non-empty strings'
                    )
            elif not (isinstance(key, str) and key):
                raise TypeError(
                    'GatherSpec.group_by items must be non-empty strings or '
                    '{"src": ..., "dst": ...} mappings'
                )
        if not all(isinstance(k, str) and k for k in order_by_):
            raise TypeError(
                'GatherSpec.order_by items must be non-empty strings'
            )
        # Mapping entries become (src, dst) pairs so the spec stays hashable
        # -- it is used as a dict key when reporting cardinalities.
        group_by_ = tuple(_store_group_key(key) for key in group_by)
        _seen = [_group_key_pair(k) for k in group_by_]
        if len(set(_seen)) != len(_seen):
            raise ValueError('GatherSpec.group_by cannot contain duplicates')
        if len(set(order_by_)) != len(order_by_):
            raise ValueError('GatherSpec.order_by cannot contain duplicates')
        if require != 'all_success':
            raise ValueError(
                'GatherSpec.require currently supports only "all_success"; '
                f'got {require!r}'
            )
        object.__setattr__(self, 'group_by', group_by_)
        object.__setattr__(self, 'order_by', order_by_)
        object.__setattr__(self, 'require', require)

    @classmethod
    def coerce(cls, data: Any) -> 'GatherSpec':
        if isinstance(data, cls):
            return data
        if isinstance(data, Mapping):
            return cls(**dict(data))
        raise TypeError(
            f'Cannot coerce {type(data).__name__} into GatherSpec: {data!r}'
        )

    def display_keys(self) -> tuple[str, ...]:
        """Human-readable group keys, e.g. ``dataset_fpath->truth_fpath``."""
        out = []
        for key in self.group_by:
            src, dst = _group_key_pair(key)
            out.append(src if src == dst else f'{src}->{dst}')
        return tuple(out)

    def source_keys(self) -> tuple[str, ...]:
        """The key resolved on each *source* instance, in order."""
        return tuple(_group_key_pair(k)[0] for k in self.group_by)

    def target_keys(self) -> tuple[str, ...]:
        """The key resolved on the *target* instance, in order."""
        return tuple(_group_key_pair(k)[1] for k in self.group_by)

    def to_dict(self) -> dict[str, Any]:
        data: dict[str, Any] = {
            'group_by': [
                {'src': k[0], 'dst': k[1]} if isinstance(k, tuple) else k
                for k in self.group_by
            ]
        }
        if self.order_by:
            data['order_by'] = list(self.order_by)
        if self.require != 'all_success':
            data['require'] = self.require
        return data


def _store_group_key(key: GroupByKey) -> StoredGroupByKey:
    """
    Put an authored ``group_by`` entry into the form :class:`GatherSpec` stores.

    A plain string names the same thing on both sides and is kept as-is. A
    ``{'src': ..., 'dst': ...}`` mapping lets each side name it in its own
    vocabulary -- a scorer whose truth port is ``truth_fpath`` can group
    predictions keyed on ``dataset_fpath`` without either node renaming a port
    to satisfy the other -- and becomes a pair, because the spec is frozen and
    used as a dict key while a mapping is unhashable.

    Callers must validate first: a mapping without both keys raises ``KeyError``
    here, where :meth:`GatherSpec.__init__` raises something explanatory.

    Args:
        key (GroupByKey): one entry as written.

    Returns:
        StoredGroupByKey

    Example:
        >>> _store_group_key('task')
        'task'
        >>> _store_group_key({'src': 'dataset_fpath', 'dst': 'truth_fpath'})
        ('dataset_fpath', 'truth_fpath')
    """
    if isinstance(key, str):
        return key
    return (key['src'], key['dst'])


def _group_key_pair(key: StoredGroupByKey) -> tuple[str, str]:
    """
    Read a stored ``group_by`` entry as ``(source_key, target_key)``.

    Args:
        key (StoredGroupByKey): one entry as :class:`GatherSpec` stores it.

    Returns:
        tuple[str, str]

    Example:
        >>> _group_key_pair('task')
        ('task', 'task')
        >>> _group_key_pair(('dataset_fpath', 'truth_fpath'))
        ('dataset_fpath', 'truth_fpath')
    """
    if isinstance(key, str):
        return (key, key)
    return key


@dataclass
class GatherConnection:
    """A template-level gather edge between an output and an input port."""

    source: Any
    target: Any
    spec: GatherSpec


def _dependency_preds(input_node: 'InputNode') -> list['IONode']:
    """
    Predecessors of an input that represent a real data dependency.

    An ``input -> input`` edge is an *alias*: the upstream node does not
    produce this value, it merely consumes the same one. Treating that as a
    dependency would queue a job the consumer does not wait on anything for,
    and give the borrower ``.pred`` / ``.succ`` links to a process that made
    nothing it reads, so aliases are excluded here. Identity is not at stake
    either way -- it hashes effective values, not dependencies.
    """
    return [pred for pred in input_node.pred if not isinstance(pred, InputNode)]


def _alias_preds(input_node: 'InputNode') -> list['InputNode']:
    """Predecessors of an input that only share its value."""
    return [pred for pred in input_node.pred if isinstance(pred, InputNode)]


def _is_gathered(port: 'IONode') -> bool:
    """
    Whether a port's value is a gather manifest.

    A template port knows only that it *has* a gather connection; the concrete
    membership arrives during compilation. Both states mean the same thing for
    lineage -- this port's value is a manifest its own job writes -- so asking
    the question in one place keeps the template graph and the compiled graph
    from disagreeing about whether an edge exists.
    """
    return (
        port._gather_connection is not None or port._gather_members is not None
    )


def _alias_origins(input_node: 'InputNode') -> list['IONode']:
    """
    Producers reached by walking this input's alias edges backwards.

    See :func:`_produced_origins`, which combines this with the input's own
    direct producers. Split out because the two are needed separately: when a
    forwarded value outranks a direct producer, the alias chain is the only
    part that still supplies anything.
    """
    recovered: dict[int, 'IONode'] = {}
    seen = {id(input_node)}
    stack = list(_alias_preds(input_node))
    while stack:
        alias = stack.pop()
        if id(alias) in seen:
            # Alias relationships are validated as acyclic elsewhere, but a
            # traversal that is only correct on a DAG is a trap for later
            # callers.
            continue
        seen.add(id(alias))
        if _is_gathered(alias):
            # A gathered port resolves to a manifest, and that manifest is
            # written by the job that owns the port -- not by any member of
            # the collection. Forwarding it therefore does create a real
            # dependency on that job, and the traversal stops here: whatever
            # the members are, they are already that job's own ancestors.
            if alias.parent is input_node.parent:
                # ... which cannot be true of the borrower itself. Such a node
                # would depend on itself, and asking for its identity would
                # recurse into the identity being computed. Reject it here
                # rather than let it surface as a RecursionError or a
                # self-edge during graph validation.
                raise ValueError(
                    f'Cannot forward the gathered input {alias.key!r} to '
                    f'{input_node.key!r} on the same process: the manifest is '
                    'written by that process, so the value cannot also be one '
                    'of its own inputs. Gather into a separate process, or '
                    'read the manifest inside the program.'
                )
            recovered[id(alias)] = alias
            continue
        for pred in _dependency_preds(alias):
            recovered[id(pred)] = pred
        stack.extend(_alias_preds(alias))
    return sorted(recovered.values(), key=lambda port: port.key)


def _produced_origins(input_node: 'InputNode') -> list['IONode']:
    """
    Every port whose product could supply this input, structurally.

    An ``input -> input`` edge forwards an already-known value, and when that
    value is externally configured or comes from a declared default there is
    nothing to wait for. But an alias may equally well forward a value some
    process *produces*, and that producer still has to run and materialize
    its artifact first. Aliasing a port must not erase the producer standing
    behind it.

    Origins are found **structurally**, by walking alias edges backwards to
    the ports they end at. Nothing is resolved along the way, so the answer
    cannot depend on node insertion order, on whether the pipeline has been
    configured yet, or on a value left over from a previously configured
    matrix row. That is what makes it the right question for the *template*
    graph, which is built before any matrix row exists.

    It is deliberately not the right question for identity. A configured port
    may take its value from somewhere that outranks a producer, and then the
    producer is not what it reads -- see :func:`_effective_origins`.

    Note that the process *holding* an aliased input is not itself an origin
    when it merely lends a value it also consumes. A *gathered* port is the
    exception: its value is the manifest that port's own job writes, so the
    process holding it really does produce the artifact being forwarded, and
    the gathered port is returned as the origin.

    Args:
        input_node (InputNode): the port to trace.

    Returns:
        list: the direct producers of this port, in declaration order,
            followed by any recovered through aliases, ordered by port key.
            Entries are :class:`OutputNode` ports, or an :class:`InputNode`
            when the origin is a gather manifest. Both answer ``.parent`` and
            ``.name``.
    """
    direct = {id(pred): pred for pred in _dependency_preds(input_node)}
    origins = list(direct.values())
    origins += [
        port for port in _alias_origins(input_node) if id(port) not in direct
    ]
    return origins


def _effective_origins(input_node: 'InputNode') -> list['IONode']:
    """
    The ports that actually supply this configured input's value.

    :func:`_produced_origins` answers what *could* reach a port. This answers
    what does, using the same precedence :meth:`IONode._resolved_value` uses:
    a gathered manifest, then this port's own configured value, then a value
    forwarded from a peer port, then an upstream product, then the declared
    default.

    Scheduling and provenance ask this one. Identity does **not**: it hashes
    the effective *value*, not the port that supplied it, so that a produced
    path and the same path written by hand are one computation. See
    :meth:`ProcessNode.depends` and the identity invariant in ``AGENTS.md``.

    Returns an empty list whenever the value is *not* produced -- gathered,
    explicitly configured, forwarded from a known value, or defaulted -- which
    is exactly when the value itself belongs in ``final_input_config``.

    Only meaningful on a configured node: it resolves values, so unlike
    :func:`_produced_origins` it must not be used to build the template graph.

    Args:
        input_node (InputNode): the port to trace.

    Returns:
        list: the supplying ports, or empty when nothing upstream supplies it.
    """
    return _effective_origins_impl(input_node, set())


def _effective_origins_impl(
    input_node: 'InputNode', seen: set[int]
) -> list['IONode']:
    if id(input_node) in seen:
        return []
    seen.add(id(input_node))
    if input_node._gather_members is not None:
        # This port's own gather. Its membership is identity-bearing through
        # ``depends['__gather__.<port>']``, not through an origin.
        return []
    if input_node._final_value is not _UNSET:
        # An explicitly configured value outranks any producer.
        return []
    if input_node._shared_value() is not _UNSET:
        # A forwarded value outranks a producer too -- but *which* value the
        # alias forwards is its own precedence question, not a structural one.
        # An alias that was itself overridden supplies a configured constant,
        # and the producer wired behind it supplies nothing to anybody. Asking
        # each source the same question is the only way to see that; walking
        # the chain structurally would report a producer that two hops of
        # overrides ago stopped being read.
        origins: dict[int, 'IONode'] = {}
        for alias in _alias_preds(input_node):
            if alias._resolved_value() is _UNSET:
                # Supplies nothing, so it cannot be the effective source.
                continue
            for port in _supplying_ports(alias, seen):
                origins[id(port)] = port
        return sorted(origins.values(), key=lambda port: port.key)
    direct = _dependency_preds(input_node)
    if direct:
        return direct
    # Nothing is forwarded and nothing is wired: the declared default, if any,
    # is a value this node owns.
    return []


def _supplying_ports(port: 'InputNode', seen: set[int]) -> list['IONode']:
    """
    The ports that produce the value ``port`` currently holds.

    Differs from :func:`_effective_origins` in one case, which is why it is
    separate: a gathered port *is* a producer as far as anyone borrowing its
    value is concerned, because its owner writes the manifest. Asked about
    itself, that same port has no origin -- its membership is identity-bearing
    through ``__gather__.<port>``.
    """
    if port._gather_members is not None:
        return [port]
    return _effective_origins_impl(port, seen)


#: The port pairs an edge may connect, and what each one means. There are only
#: three, and everything else in this module is either one of them or sugar
#: that resolves to a set of them.
_LEGAL_PORT_EDGES = {
    ('output', 'input'): 'a produced artifact',
    ('input', 'input'): 'a forwarded input value',
    ('param', 'param'): 'a forwarded algorithm parameter',
}


def _port_kind(node: Any) -> str | None:
    """
    Which of the three port kinds this is, or ``None`` for a process.

    The process/port split asks ``__node_type__`` rather than ``isinstance``
    for the reason given on :class:`Node`; the kind of a port is a plain
    ``isinstance``, since the three are siblings under :class:`IONode`.
    """
    if getattr(node, '__node_type__', None) != 'io':
        return None
    if isinstance(node, OutputNode):
        return 'output'
    if isinstance(node, ParamNode):
        return 'param'
    if isinstance(node, InputNode):
        return 'input'
    return None


def _validate_port_edge(source: Any, target: Any) -> None:
    """
    Reject a port pair that has no meaning to give the graph.

    An output wired to an output, or a parameter to an input, used to be
    recorded silently and then to mean nothing to anything that reads the
    graph. Parameter forwarding in particular predates parameter ports, so the
    old generic machinery accepted mixed edges that only failed later, during
    configuration, somewhere else entirely.

    Raises:
        TypeError: the pair is not one of :data:`_LEGAL_PORT_EDGES`.
    """
    kinds = (_port_kind(source), _port_kind(target))
    if kinds in _LEGAL_PORT_EDGES:
        return
    legal = ', '.join(
        f'{s} -> {t} ({meaning})'
        for (s, t), meaning in _LEGAL_PORT_EDGES.items()
    )
    raise TypeError(
        f'Cannot connect {source.key!r} to {target.key!r}: a '
        f'{kinds[0] or "process"} may not supply a {kinds[1] or "process"}. '
        f'The legal port edges are: {legal}.'
    )


def _connect_port(source: Any, target: Any) -> None:
    """
    The one connection primitive: an edge between two ports.

    Every other form in this module resolves to a set of calls to this. Ports
    are the only things that carry ``pred`` / ``succ`` -- a process holds no
    edges of its own, and its relationships are derived from its ports' -- so
    this is also the only function that appends one.
    """
    _validate_port_edge(source, target)
    if target not in source.succ:
        source.succ.append(target)
    if source not in target.pred:
        target.pred.append(source)


def _outgoing_ports(node: Any) -> Mapping[str, Any]:
    """The ports a connection may leave ``node`` by, keyed by port name."""
    if node.__node_type__ == 'process':
        return cast(Mapping[str, Any], node.outputs)
    return {node.name: node}


def _incoming_ports(node: Any) -> Mapping[str, Any]:
    """The ports a connection may enter ``node`` by, keyed by port name."""
    if node.__node_type__ == 'process':
        return cast(Mapping[str, Any], node.inputs)
    return {node.name: node}


def _resolve_node_pairs(source: Any, target: Any) -> list[tuple[Any, Any]]:
    """
    What a node-level connection stands for: matching names, and nothing else.

    ``producer.connect(consumer)`` is a convenience for the common shape where
    a stage's outputs and the next stage's inputs are deliberately named alike
    -- typically one major artifact each. Every output whose name is also an
    input name is connected; nothing else is. Algorithm parameters are not
    considered, because :func:`ProcessNode.param_ports` is deliberately not
    part of ``inputs``: a parameter is not data the node reads.

    Either endpoint may be a port instead of a process, which simply pins that
    side to one name. Two ports never reach here -- the caller already knows
    that pair and :func:`_connect_port` takes it directly.

    Matching is by name on both sides. It used to pair positionally, over two
    dicts that each kept their own insertion order, so a producer and consumer
    that enumerated the same names in different orders got their ports crossed
    without a word.

    Returns:
        list: the ``(output_port, input_port)`` pairs to connect.

    Raises:
        ValueError: no name is shared, so there is nothing to connect.
    """
    outputs = _outgoing_ports(source)
    inputs = _incoming_ports(target)
    common = sorted(set(outputs) & set(inputs))
    if not common:
        raise ValueError(
            f'Cannot connect {source.name!r} to {target.name!r}: they share no '
            f'port name. {source.name!r} offers {sorted(outputs)} and '
            f'{target.name!r} accepts {sorted(inputs)}. A node-level '
            'connection joins outputs to inputs of the same name; to connect '
            'ports that are named differently, name them explicitly, as in '
            'a.outputs[...].connect(b.inputs[...]).'
        )
    return [(outputs[name], inputs[name]) for name in common]


class Node(ub.NiceRepr):
    """
    Abstract base class for a Process or IO Node.
    """

    __node_type__ = 'abstract'  # used to workaround IPython isinstance issues

    def __init__(self, name: Any) -> None:
        self.name = name

    def connect(
        self,
        *others: Any,
        gather: GatherSpec | Mapping[str, Any] | None = None,
    ) -> 'Node':
        """
        Connect this node or port to ``others``.

        Two ports connect directly. Anything involving a process is resolved
        to port pairs by name first; see :func:`_resolve_node_pairs`. When
        ``gather`` is given, the edge is a compile-time many-to-one edge and
        must connect one :class:`OutputNode` to one or more
        :class:`InputNode` objects.

        Every pair is resolved and validated before any edge is added, so a
        call that raises leaves nothing half-connected.

        Returns:
            Node: ``self``, so connections can be chained.
        """
        if gather is None:
            pairs: list[tuple[Any, Any]] = []
            for other in others:
                if (
                    _port_kind(self) is not None
                    and _port_kind(other) is not None
                ):
                    pairs.append((self, other))
                else:
                    pairs.extend(_resolve_node_pairs(self, other))
            for source, target in pairs:
                _validate_port_edge(source, target)
            for source, target in pairs:
                _connect_port(source, target)
        else:
            gather_spec = GatherSpec.coerce(gather)
            if not isinstance(self, OutputNode):
                raise TypeError(
                    'Gather connections must originate from an OutputNode; '
                    f'got {type(self).__name__}'
                )
            for other in others:
                if not isinstance(other, InputNode):
                    raise TypeError(
                        'Gather connections must terminate at an InputNode; '
                        f'got {type(other).__name__}'
                    )
                if other.pred:
                    raise ValueError(
                        f'Cannot gather into {other.key!r}: it already has an '
                        'ordinary predecessor'
                    )
                if other._gather_connection is not None:
                    raise ValueError(
                        f'Input {other.key!r} already has a gather connection'
                    )
                connection = GatherConnection(self, other, gather_spec)
                self._gather_connections.append(connection)
                other._gather_connection = connection

        return self

    @property
    def key(self) -> str:
        return self.name


class _UnsetValue:
    """Singleton sentinel for a port with no explicit local value."""

    def __deepcopy__(self, memo: Any) -> '_UnsetValue':
        return self

    def __repr__(self) -> str:
        return '<unset>'


_UNSET = _UnsetValue()


def _coerce_comparable_value(value: Any) -> Any:
    """Normalize common path-like values before conflict checks."""
    if isinstance(value, os.PathLike):
        return os.fspath(value)
    return value


def _config_values_equal(left: Any, right: Any) -> bool:
    """Robust equality for values used by shared configuration ports."""
    left = _coerce_comparable_value(left)
    right = _coerce_comparable_value(right)
    try:
        equal = left == right
        if isinstance(equal, bool):
            return equal
        if hasattr(equal, 'all'):
            return bool(equal.all())
        return bool(equal)
    except Exception:
        return repr(left) == repr(right)


class IONode(Node):
    __node_type__ = 'io'

    def __nice__(self) -> str:
        return f'{self.name!r}, pred={[n.name for n in self.pred]}, succ={[n.name for n in self.succ]}'

    def __init__(
        self, name: str, parent: Any, default_value: Any = _UNSET
    ) -> None:
        super().__init__(name)
        # Only ports carry graph edges. A process has no connections of its
        # own: its relationships are derived from its ports', which is why
        # these live here rather than on Node.
        self.pred: list[Any] = []
        self.succ: list[Any] = []
        self.parent = parent
        self.default_value = default_value
        self._final_value = _UNSET
        self._template_value = None
        self._gather_connection: GatherConnection | None = None
        self._gather_members: list[Any] | None = None

    def _shared_value_predecessors(self) -> list[Any]:
        """Predecessors that forward an already-known configuration value."""
        return []

    def _shared_value(self) -> Any:
        predecessors = self._shared_value_predecessors()
        if not predecessors:
            return _UNSET
        # A predecessor that resolves to nothing supplies nothing. Only ports
        # that actually carry a value can agree or disagree about it.
        bound = [(pred, pred._resolved_value()) for pred in predecessors]
        bound = [item for item in bound if item[1] is not _UNSET]
        if not bound:
            return _UNSET
        first = bound[0][1]
        if not all(
            _config_values_equal(first, value) for _pred, value in bound[1:]
        ):
            bindings = {pred.key: value for pred, value in bound}
            raise ValueError(
                f'Conflicting shared values for {self.key!r}: {bindings!r}'
            )
        return first

    @property
    def final_value(self) -> Any:
        """
        The value this port resolves to, or ``None`` when nothing supplies one.

        Use :func:`_resolved_value` when the difference between "resolved to
        ``None``" and "nothing supplied a value" matters.
        """
        value = self._resolved_value()
        return None if value is _UNSET else value

    def _resolved_value(self) -> Any:
        """
        Resolve this port, returning ``_UNSET`` when nothing supplies a value.

        The precedence is: a gathered manifest, this port's own configured
        value, a shared value forwarded from a peer port, a value produced by
        an upstream process, and finally the declared default.
        """
        if self._gather_members is not None:
            return self.gather_manifest_fpath
        local_value = self._final_value
        shared_value = self._shared_value()
        if local_value is not _UNSET and shared_value is not _UNSET:
            if not _config_values_equal(local_value, shared_value):
                source_values = {
                    pred.key: pred.final_value
                    for pred in self._shared_value_predecessors()
                }
                raise ValueError(
                    f'Conflicting explicit and shared values for {self.key!r}: '
                    f'explicit={local_value!r}, shared={source_values!r}'
                )
            return local_value
        if local_value is not _UNSET:
            return local_value
        if shared_value is not _UNSET:
            return shared_value

        # Produced inputs preserve the historical behavior: one predecessor
        # forwards one path, and multiple predecessors form a collection.
        shared_predecessors = self._shared_value_predecessors()
        produced_preds = [
            pred for pred in self.pred if pred not in shared_predecessors
        ]
        if produced_preds:
            if len(produced_preds) == 1:
                return produced_preds[0].final_value
            return [pred.final_value for pred in produced_preds]
        return self.default_value

    @final_value.setter
    def final_value(self, value: Any) -> None:
        self._final_value = value

    @property
    def key(self) -> str:
        return self.parent.key + '.' + self.name

    @property
    def gather_manifest_fpath(self) -> Any:
        if self._gather_members is None:
            raise AttributeError(
                f'{self.key!r} is not a configured gather input'
            )
        return self.parent.final_node_dpath / '_gather' / f'{self.name}.txt'

    def gather_manifest_text(self) -> str:
        if self._gather_members is None:
            raise AttributeError(
                f'{self.key!r} is not a configured gather input'
            )
        paths = [
            os.fspath(member.final_value) for member in self._gather_members
        ]
        for path in paths:
            if '\n' in path:
                raise ValueError(
                    f'Gathered path contains a newline and cannot be represented '
                    f'in a path manifest: {path!r}'
                )
        return ''.join(path + '\n' for path in paths)


class InputNode(IONode):
    def _shared_value_predecessors(self) -> list[Any]:
        return [pred for pred in self.pred if isinstance(pred, InputNode)]


class ParamNode(IONode):
    """A connectable algorithm parameter, distinct from a filesystem input."""

    def _shared_value_predecessors(self) -> list[Any]:
        return [pred for pred in self.pred if isinstance(pred, ParamNode)]


class OutputNode(IONode):
    def __init__(self, name: str, parent: Any) -> None:
        super().__init__(name, parent)
        self._gather_connections: list[GatherConnection] = []

    # Redefine as a full read-write property (getter + setter) so it remains a
    # Liskov-compatible override of IONode's read-write ``final_value`` -- a
    # plain ``@property`` would drop the setter and trip the type checkers.
    @property
    def final_value(self) -> Any:
        # return self.parent._finalize_templates()['out_paths'][self.name]
        return self.parent.final_out_paths[self.name]

    @final_value.setter
    def final_value(self, value: Any) -> None:
        self._final_value = value

    def _resolved_value(self) -> Any:
        # An output port always resolves: the process defines where it writes.
        return self.final_value

    @property
    def template_value(self) -> Any:
        return self.parent.template_out_paths[self.name]
